#Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: java-app-argocd

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-argocd
  namespace: java-app-argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app-argocd
  template:
    metadata:
      labels:
        app: java-app-argocd
    spec:
      containers:
      - name: java-app-argocd
        image: khushbub/application_img_argocd:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
